module.exports = {
    URL_HASHED_SUCCESSFULLY: "URL_HASHED_SUCCESSFULLY",
    INVALID_CODE: "INVALID_CODE",
    USER_NOT_EXIST: "USER_NOT_EXIST",
    USER_NOT_AUTHORIZED: "USER_NOT_AUTHORIZED",
    EMAIL_ALREADY_ASSOCIATED_WITH_ANOTHER_ACCOUNT: "EMAIL_ALREADY_ASSOCIATED_WITH_ANOTHER_ACCOUNT",
    INVALID_AUTH_TOKEN: "INVALID_AUTH_TOKEN",
    INVALID_LOGIN_CREDENTIALS: "INVALID_LOGIN_CREDENTIALS",
    USER_LOGGEDIN_SUCCESSFULLY: "USER_LOGGEDIN_SUCCESSFULLY",
    USER_SIGNUP_SUCCESSFULLY: "USER_SIGNUP_SUCCESSFULLY",
    URLS_FETCHED_SUCCESSFULLY: "URLS_FETCHED_SUCCESSFULLY"
}